spring.application.name=OrderService
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/orders_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
paypal.client.id=ATg61FxAC7q5KqS271VwDa42GpqTFoEwB_ZXciTj6wEZ7PsVTjKlw-T0fcdtk5gs24lQiUXuVDsP0HFh
paypal.client.secret=EErOxxfzvOE9knKEChV_MaR5p05-xaVspadxZffRev-M8_pD36hhArGRSfmcvY-P9xdTodd5Gh0ovHMF
paypal.mode=sandbox